import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get('window');

export const globalColors = {
    background: '#E0E5EC',
    primary: '#080099',
    accent: '#080099',
    text: '#333333',
    texTitle: '#e3dddd',
    lightShadow: '#FFFFFF',
    darkShadow: '#A3B1C6',
    questionBackground: '#D8DDE4',
}

export const globalStyles = StyleSheet.create({
    buttonText: {
        color: globalColors.texTitle,
        fontSize: 18,
        fontWeight: '600',
    },
    buttonsBanner: {
        display: 'flex',
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'space-around',
        marginVertical: 20,
    },
    placeholderText: {
        fontSize: 16,
        color: '#888',
    },
    inputText: {
        fontSize: 16,
        color: globalColors.text,
    },
    CapTitle: {
        width: '100%',
        backgroundColor: globalColors.primary,
        padding: 15,
        paddingTop: 25,
        borderRadius: 15,
        textAlign: 'center',
        marginBottom: 20,
        color: globalColors.background,
        fontSize: 22,
        fontWeight: 'bold',
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 4, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 5,
        elevation: 5,
    },
    HomeScreenContainer: {
        flex: 1,
        flexDirection: "column",
        alignItems: 'center',
        justifyContent: 'center',
        gap: 200,
        padding: 20,
        backgroundColor: globalColors.background,
    },
    fab: {
        backgroundColor: globalColors.accent,
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        right: 20,
        bottom: 20,
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 4, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 5,
        elevation: 5,
    },
    FomsContainer: {
        flexGrow: 1,
        padding: 20,
        backgroundColor: globalColors.background,
    },
    PrimaryButton: {
        backgroundColor: globalColors.primary,
        borderRadius: 15,
        padding: 15,
        width: width * 0.8,
        alignItems: 'center',
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 50, height: 50 },
        shadowOpacity: 0.2,
        shadowRadius: 50,
        elevation: 5,
    },
    questionTitle: {
        color: globalColors.text,
        marginBottom: 20,
        fontSize: 20,
        fontWeight: '600',
        textAlign: 'left',
        paddingHorizontal: 10,
    },
    Title: {
        fontSize: 24,
        fontWeight: '600',
        color: globalColors.texTitle,
        textAlign: 'center',
        marginBottom: 20,
    },
    Titleout: {
        fontSize: 24,
        fontWeight: '600',
        color: globalColors.text,
        textAlign: 'center',
        marginBottom: 20,
    },
    input: {
        height: 50,
        marginBottom: 20,
        paddingHorizontal: 20,
        backgroundColor: globalColors.questionBackground,
        color: globalColors.text,
        borderRadius: 15,
        fontSize: 16,
        fontWeight: '500',
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    inputDate: {
        height: 50,
        marginBottom: 20,
        paddingHorizontal: 20,
        paddingTop: 12,
        backgroundColor: globalColors.questionBackground,
        color: globalColors.text,
        borderRadius: 15,
        fontSize: 16,
        fontWeight: '500',
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    picker: {
        borderRadius: 15,
        backgroundColor: globalColors.questionBackground,
        marginBottom: 20,
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    radioButton: {
        flexDirection: 'row',
        alignItems: 'center',
        width: "100%",
        marginVertical: 8,
    },
    radioButton_2: {
        flexDirection: 'column',
        alignItems: 'flex-start',
        width: "100%",
        marginVertical: 8,
    },
    ButtonSelector: {
        height: 24,
        width: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: globalColors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
        backgroundColor: globalColors.background,
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
        elevation: 2,
    },
    ButtonSelectorSelected: {
        height: 14,
        width: 14,
        borderRadius: 7,
        backgroundColor: globalColors.primary,
    },
    optionsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    checkboxContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 8,
        width: '48%',
        backgroundColor: globalColors.questionBackground,
        borderRadius: 15,
        padding: 12,
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    checkbox: {
        height: 24,
        width: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: globalColors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
        backgroundColor: globalColors.background,
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
        elevation: 2,
    },
    checkboxSelected: {
        height: 14,
        width: 14,
        borderRadius: 7,
        backgroundColor: globalColors.primary,
    },
    optionText: {
        flex: 1,
        fontSize: 14,
        color: globalColors.text,
        textAlign: 'left',
    },
    otherInputContainer: {
        marginTop: 15,
        width: '100%',
    },
    otherInput: {
        borderWidth: 1,
        borderColor: globalColors.primary,
        borderRadius: 15,
        padding: 12,
        marginBottom: 10,
        width: '100%',
        fontSize: 16,
        backgroundColor: globalColors.questionBackground,
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    addButton: {
        backgroundColor: globalColors.accent,
        padding: 12,
        borderRadius: 15,
        alignItems: 'center',
        width: '100%',
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    addButtonText: {
        color: globalColors.background,
        fontSize: 16,
        fontWeight: '600',
    },
    expandingInput: {
        minHeight: 40,
        maxHeight: 200,
        paddingTop: 12,
        paddingBottom: 12,
        paddingHorizontal: 15,
        textAlignVertical: 'top',
        backgroundColor: globalColors.questionBackground,
        borderRadius: 15,
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    subOptionsContainer: {
        marginLeft: 24,
        marginTop: 10,
    },
    counterInput: {
        borderWidth: 1,
        borderColor: globalColors.primary,
        borderRadius: 15,
        padding: 12,
        marginTop: 8,
        width: '50%',
        fontSize: 16,
        backgroundColor: globalColors.questionBackground,
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    errorText: {
        color: globalColors.accent,
        marginTop: 5,
        fontSize: 14,
    },
    nestedOptionWrapper: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginVertical: 8,
        paddingVertical: 12,
        paddingHorizontal: 15,
        backgroundColor: globalColors.questionBackground,
        borderRadius: 15,
        width: '100%',
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    nestedCheckmark: {
        height: 24,
        width: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: globalColors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
        marginTop: 2,
        backgroundColor: globalColors.background,
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
        elevation: 2,
    },
    nestedCheckmarkSelected: {
        height: 14,
        width: 14,
        borderRadius: 7,
        backgroundColor: globalColors.primary,
    },
    nestedOptionLabel: {
        flex: 1,
        fontSize: 16,
        color: globalColors.text,
        lineHeight: 22,
    },
    nestedSubOptionsContainer: {
        marginLeft: 36,
        marginTop: 10,
    },
    nestedQuestionHeader: {
        color: globalColors.text,
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 12,
        marginTop: 16,
        textAlign: 'left',
        paddingHorizontal: 10,
    },
    nestedCounterField: {
        borderWidth: 1,
        borderColor: globalColors.primary,
        borderRadius: 15,
        padding: 12,
        marginTop: 8,
        width: '50%',
        fontSize: 16,
        backgroundColor: globalColors.questionBackground,
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: globalColors.background,
    },
    dateContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    dateField: {
        width: '48%',
    },
    dateLabel: {
        fontSize: 14,
        marginBottom: 5,
        color: globalColors.text,
    },
    timeContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    timeField: {
        width: '30%',
    },
    timeLabel: {
        fontSize: 14,
        marginBottom: 5,
        color: globalColors.text,
    },
    amPmContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '30%',
    },
    amPmButton: {
        backgroundColor: globalColors.background,
        borderRadius: 10,
        padding: 10,
        width: '48%',
        alignItems: 'center',
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    amPmButtonSelected: {
        backgroundColor: globalColors.primary,
    },
    amPmButtonText: {
        color: globalColors.text,
        fontWeight: 'bold',
    },
    radioContainer: {
        marginBottom: 20,
    },
    radio: {
        height: 24,
        width: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: globalColors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
        backgroundColor: globalColors.background,
        shadowColor: globalColors.darkShadow,
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
        elevation: 2,
    },
    radioSelected: {
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: globalColors.primary,
    },
    radioLabel: {
        fontSize: 16,
        color: globalColors.text,
    },
    descriptioText: {
        marginLeft: 10,
        marginBottom: 5
    }
});